### ISSUE TITLE
NPE when Type Mapping is not available

### ISSUE THREAD

**Issue by dzuvic** [dzuvic/jtsgen#34]
```
java.lang.NullPointerException: type
	at java.util.Objects.requireNonNull(Objects.java:228)
	at dz.jtsgen.processor.model.TSRegularMemberBuilder.<init>(TSRegularMemberBuilder.java:26)
	at dz.jtsgen.processor.model.TSRegularMemberBuilder.of(TSRegularMemberBuilder.java:183)
	at dz.jtsgen.processor.jtp.conv.JavaTypeElementExtractingVisitor.visitExecutable(JavaTypeElementExtractingVisitor.java:100)
	at dz.jtsgen.processor.jtp.conv.JavaTypeElementExtractingVisitor.visitExecutable(JavaTypeElementExtractingVisitor.java:43)
```

**Comment by dzuvic** [comment]
The arrays were not supported and caused this NPE. This is fixed by adding simple support for Java arrays. .
